version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /var/lib/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: ./install-dependencies.sh
      timeout: 300
      runas: root
    - location: ./tomcat.sh
      timeout: 300
      runas: root
