version: 0.0
os: linux
files:
  - source: /target/*.war
    destination: /var/lib/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: ./stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: ./install_dependencies.sh
      timeout: 300
      runas: root
    - location: ./install_tom.sh
      timeout: 300
      runas: root
  Install:
    - location: ./prepare_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: ./validate_service.sh
      timeout: 300
      runas: root