version: 0.0
os: linux
files:
  - source: /target/*.jar
    destination: /var/lib/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    # - location: scripts/install_dependencies.sh
    #   timeout: 300
    #   runas: root
    # - location: scripts/install_tomcat.sh
    #   timeout: 300
    #   runas: root
  # Install:
  #   - location: scripts/prepare_application.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: scripts/set_permissions.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root