version: 0.2

phases:
  install: 
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing Maven"
      - yum install -y maven
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the project"
      - mvn clean install -f src/pom.xml
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - '**/target/*.war'
  discard-paths: yes