version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Preparing for build"
  build:
    commands:
      - echo "Building the project"
      - mvn clean install -f pom.xml
  post_build:
    commands:
      - echo "Starting Jetty server"
      - mvn jetty:run -f web/app/pom.xml &
artifacts:
  files:
    - '**/*'